//DB_HOST=31.130.132.122

/* import 'package:dotenv/dotenv.dart';
import 'package:postgres/postgres.dart';

final _env = DotEnv()..load();

class Database {
  static final conn = Connection.openFromUrl(
    'postgresql://${_env['DB_USER']}:${_env['DB_PASSWORD']}@${_env['DB_HOST']}:${int.parse(_env['DB_PORT']!)}/${_env['DB_NAME']}',
  );

  static Future<Connection> getConnection() async {
    return conn;
  }
}
 */
/* CREATE TABLE "tables" (    
    rdate TEXT PRIMARY KEY,
    date TEXT NOT NULL,
    log TEXT[] NOT NULL DEFAULT '{}',
    ald TEXT[] NOT NULL DEFAULT '{}',
    alr TEXT[] NOT NULL DEFAULT '{}',
    rcf TEXT[] NOT NULL DEFAULT '{}',
    d1 INTEGER NOT NULL,
    d2 TEXT NOT NULL,
    d3 INTEGER NOT NULL,
    d4 INTEGER NOT NULL,
    d5 INTEGER NOT NULL,
    d6 INTEGER NOT NULL,
    d7 INTEGER NOT NULL,
    d8 INTEGER NOT NULL,
    d9 INTEGER NOT NULL,
    d10 INTEGER NOT NULL,
    d11 INTEGER NOT NULL,
    d12 INTEGER NOT NULL,
    d13 INTEGER NOT NULL,
    d14 INTEGER NOT NULL,
    d15 INTEGER NOT NULL,
    d16 INTEGER NOT NULL,
    d100 INTEGER,
    d101 INTEGER,
    d102 INTEGER,
    d103 INTEGER,
    d104 INTEGER,
    d105 INTEGER,
    d106 INTEGER,
    d107 INTEGER,
    d108 TEXT,
    d109 TEXT,
    d110 TEXT,
    td1 TEXT NOT NULL,
    td2 TEXT NOT NULL,
    td3 TEXT NOT NULL,
    td4 TEXT NOT NULL,
    td5 TEXT NOT NULL,
    t2d6 INTEGER NOT NULL,
    t2d7 INTEGER NOT NULL,
    t2d8 INTEGER NOT NULL,
    t2d9 INTEGER NOT NULL,
    t2d10 INTEGER NOT NULL,
    t2d11 INTEGER NOT NULL,
    t2d12 INTEGER NOT NULL,
    t2d100 TEXT,
    t2d101 TEXT,
    t2d102 TEXT,
    t2d103 INTEGER,
    t2d104 INTEGER,
    t2d105 INTEGER,
    t2d106 INTEGER,
    t2d107 INTEGER,
    t2cls TEXT[] NOT NULL DEFAULT '{}',
    t3d1 INTEGER NOT NULL,
    t3d2 INTEGER NOT NULL,
    t3d3 INTEGER NOT NULL,
    t3d4 INTEGER NOT NULL,
    t3d5 INTEGER NOT NULL,
    t3d6 INTEGER NOT NULL,
    t3d100 INTEGER,
    t3d101 INTEGER,
    t3d102 INTEGER,
    t3d103 INTEGER,
    t4zap TEXT[] NOT NULL DEFAULT '{}',
    t5d1 TEXT NOT NULL,
    t5d2 TEXT NOT NULL,
    t5d3 TEXT NOT NULL,
    t5d4 TEXT NOT NULL,
    t5d5 TEXT NOT NULL,
    t5d6 TEXT NOT NULL,
    t5d7 TEXT NOT NULL,
    t5d100 TEXT,
    t5d101 TEXT,
    t5d102 TEXT,
    t5d103 TEXT,
    t5d104 TEXT,
    t6d1 TEXT NOT NULL,
    t6d2 TEXT NOT NULL,
    t6d3 TEXT NOT NULL,
    t6d4 TEXT NOT NULL,
    t6d5 TEXT NOT NULL,
    t6d6 TEXT NOT NULL,
    t6d100 TEXT,
    t6d101 TEXT,
    t6d102 TEXT,
    t6d103 TEXT,
    t6d104 TEXT,
    t7 TEXT[] NOT NULL DEFAULT '{}',
    t100 TEXT[],
    t101 TEXT[],
    t102 TEXT[],
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
); */
